
import type { GuardianScenario, GuardianScenarioId } from "../types";
import { isoAt } from "./scoringUtils";

export const guardianScenarios: GuardianScenario[] = [
  {
    id: "low_risk",
    label: "An toàn",
    summary: "Thiết bị quen, người nhận quen, số tiền nằm trong nhịp giao dịch thường ngày.",
    expectedAction: "allow",
    transaction: {
      userId: "user_frequent",
      amountVnd: 500_000,
      recipientId: "trusted_nguyen_van_b",
      recipientName: "Nguyễn Văn B",
      recipientAccount: "19038472910",
      recipientBank: "Ngân hàng liên kết",
      content: "Huynh Phuoc Phu chuyen tien",
      timestamp: isoAt(14, 30),
      location: "Da Nang",
      priorActions: ["login_face_id", "view_balance"],
      deviceInfo: {
        deviceId: "iphone-known-001",
        isNew: false,
        hasVPN: false,
        isEmulator: false,
        isRooted: false,
        ipReputation: "normal",
      },
      sessionInfo: { sessionId: "sess-low", ageSeconds: 420, loginMethod: "face_id" },
    },
    userProfile: {
      userId: "user_frequent",
      label: "Giao dịch thường xuyên",
      knownRecipients: ["trusted_nguyen_van_b", "family_001"],
      verifiedLocations: ["Da Nang", "Ho Chi Minh City"],
      typicalLocations: ["Da Nang"],
      typicalHours: [8, 9, 10, 11, 13, 14, 15, 16, 17, 18],
      typicalAmounts: { median: 450_000, p75: 1_200_000, p95: 2_500_000 },
      recentTransferCount1h: 1,
    },
    beneficiary: {
      recipientId: "trusted_nguyen_van_b",
      isNewRecipient: false,
      hasBeenReported: false,
      isMuleCluster: false,
      isTrusted: true,
    },
  },
  {
    id: "medium_risk",
    label: "Cảnh báo mềm",
    summary: "Số tiền cao hơn baseline của người dùng ít giao dịch, nhưng thiết bị và người nhận vẫn quen.",
    expectedAction: "warn",
    transaction: {
      userId: "user_low_activity",
      amountVnd: 3_000_000,
      recipientId: "trusted_nguyen_van_b",
      recipientName: "Nguyễn Văn B",
      recipientAccount: "19038472910",
      recipientBank: "Ngân hàng liên kết",
      content: "Chuyen tien sinh hoat",
      timestamp: isoAt(15, 10),
      location: "Da Nang",
      priorActions: ["login_password", "view_balance", "open_transfer"],
      deviceInfo: {
        deviceId: "iphone-known-001",
        isNew: false,
        hasVPN: false,
        isEmulator: false,
        isRooted: false,
        ipReputation: "normal",
      },
      sessionInfo: { sessionId: "sess-medium", ageSeconds: 260, loginMethod: "password" },
    },
    userProfile: {
      userId: "user_low_activity",
      label: "Ít giao dịch",
      knownRecipients: ["trusted_nguyen_van_b"],
      verifiedLocations: ["Da Nang"],
      typicalLocations: ["Da Nang"],
      typicalHours: [9, 10, 11, 14, 15, 16],
      typicalAmounts: { median: 300_000, p75: 800_000, p95: 2_000_000 },
      recentTransferCount1h: 1,
    },
    beneficiary: {
      recipientId: "trusted_nguyen_van_b",
      isNewRecipient: false,
      hasBeenReported: false,
      isMuleCluster: false,
      isTrusted: true,
    },
  },
  {
    id: "high_risk",
    label: "Nguy cơ cao",
    summary: "Thiết bị mới, người nhận mới và số tiền vượt P95 cần trì hoãn để xác minh.",
    expectedAction: "delay",
    transaction: {
      userId: "user_frequent",
      amountVnd: 15_000_000,
      recipientId: "new_shopmall",
      recipientName: "ShopMall Global",
      recipientAccount: "88884920412",
      recipientBank: "Co-opBank",
      content: "Thanh toan don hang",
      timestamp: isoAt(21, 35),
      location: "Da Nang",
      priorActions: ["login_password", "add_new_recipient", "open_transfer"],
      deviceInfo: {
        deviceId: "iphone-new-demo",
        isNew: true,
        hasVPN: false,
        isEmulator: false,
        isRooted: false,
        ipReputation: "suspicious",
      },
      sessionInfo: { sessionId: "sess-high", ageSeconds: 90, loginMethod: "password" },
    },
    userProfile: {
      userId: "user_frequent",
      label: "Giao dịch thường xuyên",
      knownRecipients: ["trusted_nguyen_van_b", "family_001"],
      verifiedLocations: ["Da Nang", "Ho Chi Minh City"],
      typicalLocations: ["Da Nang"],
      typicalHours: [8, 9, 10, 11, 13, 14, 15, 16, 17, 18],
      typicalAmounts: { median: 450_000, p75: 1_200_000, p95: 2_500_000 },
      recentTransferCount1h: 2,
    },
    beneficiary: {
      recipientId: "new_shopmall",
      isNewRecipient: true,
      hasBeenReported: false,
      isMuleCluster: false,
      isTrusted: false,
    },
  },
  {
    id: "critical_risk",
    label: "Nghiêm trọng",
    summary: "Giao dịch 02:13, thiết bị mới, VPN, vị trí lạ, người nhận mới và số tiền rất cao.",
    expectedAction: "block",
    transaction: {
      userId: "user_low_activity",
      amountVnd: 50_000_000,
      recipientId: "mule_cluster_042",
      recipientName: "ShopMall Global",
      recipientAccount: "88884920412",
      recipientBank: "Co-opBank",
      content: "Dau tu gap",
      timestamp: isoAt(2, 13),
      location: "Singapore",
      priorActions: ["login_password", "add_new_recipient", "increase_limit", "open_transfer"],
      deviceInfo: {
        deviceId: "android-new-vpn",
        isNew: true,
        hasVPN: true,
        isEmulator: false,
        isRooted: false,
        ipReputation: "bad",
      },
      sessionInfo: { sessionId: "sess-critical", ageSeconds: 55, loginMethod: "password" },
    },
    userProfile: {
      userId: "user_low_activity",
      label: "Ít giao dịch",
      knownRecipients: ["trusted_nguyen_van_b"],
      verifiedLocations: ["Da Nang"],
      typicalLocations: ["Da Nang"],
      typicalHours: [9, 10, 11, 14, 15, 16],
      typicalAmounts: { median: 300_000, p75: 800_000, p95: 2_000_000 },
      recentTransferCount1h: 4,
    },
    beneficiary: {
      recipientId: "mule_cluster_042",
      isNewRecipient: true,
      hasBeenReported: true,
      isMuleCluster: true,
      isTrusted: false,
    },
  },
  {
    id: "false_positive",
    label: "False positive",
    summary: "Vị trí lạ do đi du lịch nhưng từng được xác minh, nên cảnh báo thay vì khóa.",
    expectedAction: "warn",
    transaction: {
      userId: "user_anomalous",
      amountVnd: 1_000_000,
      recipientId: "trusted_nguyen_van_b",
      recipientName: "Nguyễn Văn B",
      recipientAccount: "19038472910",
      recipientBank: "Ngân hàng liên kết",
      content: "Chuyen tien tu Da Lat",
      timestamp: isoAt(19, 20),
      location: "Da Lat",
      priorActions: ["login_face_id", "travel_location_verified", "open_transfer"],
      deviceInfo: {
        deviceId: "iphone-known-001",
        isNew: false,
        hasVPN: false,
        isEmulator: false,
        isRooted: false,
        ipReputation: "normal",
      },
      sessionInfo: { sessionId: "sess-false-positive", ageSeconds: 600, loginMethod: "face_id" },
    },
    userProfile: {
      userId: "user_anomalous",
      label: "Du lịch đã xác minh",
      knownRecipients: ["trusted_nguyen_van_b"],
      verifiedLocations: ["Da Nang", "Da Lat"],
      typicalLocations: ["Da Nang"],
      typicalHours: [8, 9, 10, 11, 14, 15, 16, 19],
      typicalAmounts: { median: 600_000, p75: 1_000_000, p95: 1_800_000 },
      recentTransferCount1h: 1,
    },
    beneficiary: {
      recipientId: "trusted_nguyen_van_b",
      isNewRecipient: false,
      hasBeenReported: false,
      isMuleCluster: false,
      isTrusted: true,
    },
  },
  {
    id: "feedback_attack",
    label: "Feedback attack",
    summary: "Kẻ gian cố xác nhận nhiều lần trong một phiên rủi ro cao, nên không được giảm risk.",
    expectedAction: "delay",
    transaction: {
      userId: "user_frequent",
      amountVnd: 8_000_000,
      recipientId: "new_promo_account",
      recipientName: "Tài khoản ưu đãi lạ",
      recipientAccount: "77771020412",
      recipientBank: "BIDV",
      content: "Nhan thuong khan",
      timestamp: isoAt(22, 45),
      location: "Da Nang",
      priorActions: [
        "login_password",
        "add_new_recipient",
        "confirm_warning",
        "confirm_warning",
        "retry_transfer",
      ],
      deviceInfo: {
        deviceId: "iphone-new-demo",
        isNew: true,
        hasVPN: false,
        isEmulator: false,
        isRooted: false,
        ipReputation: "suspicious",
      },
      sessionInfo: { sessionId: "sess-feedback", ageSeconds: 80, loginMethod: "password" },
    },
    userProfile: {
      userId: "user_frequent",
      label: "Giao dịch thường xuyên",
      knownRecipients: ["trusted_nguyen_van_b", "family_001"],
      verifiedLocations: ["Da Nang", "Ho Chi Minh City"],
      typicalLocations: ["Da Nang"],
      typicalHours: [8, 9, 10, 11, 13, 14, 15, 16, 17, 18],
      typicalAmounts: { median: 450_000, p75: 1_200_000, p95: 2_500_000 },
      recentTransferCount1h: 3,
    },
    beneficiary: {
      recipientId: "new_promo_account",
      isNewRecipient: true,
      hasBeenReported: false,
      isMuleCluster: false,
      isTrusted: false,
    },
  },
  {
    id: "scam_remote_access",
    label: "Lừa đảo: Cài app lạ chứa mã độc (Khóa L2)",
    summary: "Mô phỏng kẻ gian điều khiển từ xa bằng thiết bị lạ có VPN quẹt 50.000.000đ sang tài khoản rác lúc 2h sáng.",
    expectedAction: "block",
    transaction: {
      userId: "CID-001",
      amountVnd: 50_000_000,
      recipientId: "mule_cluster_001",
      recipientName: "TÀI KHOẢN MULE RỦI RO",
      recipientAccount: "88884920412",
      recipientBank: "Co-opBank",
      content: "Nop phat thue",
      timestamp: isoAt(2, 13),
      location: "Singapore",
      priorActions: ["login_password", "add_new_recipient", "open_transfer"],
      deviceInfo: {
        deviceId: "android-new-vpn",
        isNew: true,
        hasVPN: true,
        isEmulator: false,
        isRooted: false,
        ipReputation: "bad",
      },
      sessionInfo: { sessionId: "sess-scam-remote", ageSeconds: 45, loginMethod: "password" },
    },
    userProfile: {
      userId: "CID-001",
      label: "Nguyễn Minh An",
      knownRecipients: ["trusted_nguyen_van_b", "family_001"],
      verifiedLocations: ["Ha Noi"],
      typicalLocations: ["Ha Noi"],
      typicalHours: [8, 9, 10, 12, 19, 20, 21],
      typicalAmounts: { median: 300_000, p75: 1_200_000, p95: 2_000_000 },
      recentTransferCount1h: 4,
    },
    beneficiary: {
      recipientId: "mule_cluster_001",
      isNewRecipient: true,
      hasBeenReported: true,
      isMuleCluster: true,
      isTrusted: false,
    },
  },
  {
    id: "scam_fake_job",
    label: "Lừa đảo: Tuyển CTV giật đơn hàng online (Tạm giữ)",
    summary: "Khách nạp tiền số lượng lớn 15.000.000đ đến tài khoản mới bị gắn cờ rủi ro theo hướng dẫn của kẻ gian.",
    expectedAction: "delay",
    transaction: {
      userId: "CID-001",
      amountVnd: 15_000_000,
      recipientId: "scam_fake_merchant",
      recipientName: "SHOPMALL GLOBAL",
      recipientAccount: "99992019482",
      recipientBank: "BIDV",
      content: "Thanh toan don hang giat don",
      timestamp: isoAt(21, 35),
      location: "Ha Noi",
      priorActions: ["login_password", "add_new_recipient", "open_transfer"],
      deviceInfo: {
        deviceId: "iphone-new-demo",
        isNew: true,
        hasVPN: false,
        isEmulator: false,
        isRooted: false,
        ipReputation: "suspicious",
      },
      sessionInfo: { sessionId: "sess-scam-job", ageSeconds: 90, loginMethod: "password" },
    },
    userProfile: {
      userId: "CID-001",
      label: "Nguyễn Minh An",
      knownRecipients: ["trusted_nguyen_van_b", "family_001"],
      verifiedLocations: ["Ha Noi"],
      typicalLocations: ["Ha Noi"],
      typicalHours: [8, 9, 10, 12, 19, 20, 21],
      typicalAmounts: { median: 300_000, p75: 1_200_000, p95: 2_000_000 },
      recentTransferCount1h: 4,
    },
    beneficiary: {
      recipientId: "scam_fake_merchant",
      isNewRecipient: true,
      hasBeenReported: false,
      isMuleCluster: false,
      isTrusted: false,
    },
  },
  {
    id: "scam_phishing",
    label: "Lừa đảo: Link khuyến mãi giả mạo (Xác thực Face ID)",
    summary: "Kẻ gian quẹt thẻ online 10.000.000đ qua link phishing trúng thưởng từ thiết bị mới ở nước ngoài.",
    expectedAction: "step_up",
    transaction: {
      userId: "CID-001",
      amountVnd: 10_000_000,
      recipientId: "scam_phishing_acct",
      recipientName: "TÀI KHOẢN KHUYẾN MÃI LẠ",
      recipientAccount: "77771020412",
      recipientBank: "Agribank",
      content: "Nhan thuong tri an",
      timestamp: isoAt(11, 45),
      location: "Singapore",
      priorActions: ["login_password", "open_transfer"],
      deviceInfo: {
        deviceId: "iphone-new-sg",
        isNew: true,
        hasVPN: false,
        isEmulator: false,
        isRooted: false,
        ipReputation: "suspicious",
      },
      sessionInfo: { sessionId: "sess-scam-phishing", ageSeconds: 120, loginMethod: "password" },
    },
    userProfile: {
      userId: "CID-001",
      label: "Nguyễn Minh An",
      knownRecipients: ["trusted_nguyen_van_b", "family_001"],
      verifiedLocations: ["Ha Noi"],
      typicalLocations: ["Ha Noi"],
      typicalHours: [8, 9, 10, 12, 19, 20, 21],
      typicalAmounts: { median: 300_000, p75: 1_200_000, p95: 2_000_000 },
      recentTransferCount1h: 4,
    },
    beneficiary: {
      recipientId: "scam_phishing_acct",
      isNewRecipient: true,
      hasBeenReported: false,
      isMuleCluster: false,
      isTrusted: false,
    },
  },
  {
    id: "scam_romance",
    label: "Lừa đảo: Sàn đầu tư ảo & Tình cảm (Cảnh báo + Checklist)",
    summary: "Khách tự chuyển khoản 8.000.000đ bằng thiết bị quen thuộc đến tài khoản bị nghi ngờ thuộc mạng lưới rửa tiền.",
    expectedAction: "warn",
    transaction: {
      userId: "CID-001",
      amountVnd: 8_000_000,
      recipientId: "scam_romance_mule",
      recipientName: "TÀI KHOẢN ĐẦU TƯ SÀN VÀNG",
      recipientAccount: "66661902847",
      recipientBank: "Vietcombank",
      content: "Nap tien dau tu",
      timestamp: isoAt(20, 15),
      location: "Ha Noi",
      priorActions: ["login_face_id", "open_transfer"],
      deviceInfo: {
        deviceId: "iphone-known-001",
        isNew: false,
        hasVPN: false,
        isEmulator: false,
        isRooted: false,
        ipReputation: "normal",
      },
      sessionInfo: { sessionId: "sess-scam-romance", ageSeconds: 300, loginMethod: "face_id" },
    },
    userProfile: {
      userId: "CID-001",
      label: "Nguyễn Minh An",
      knownRecipients: ["trusted_nguyen_van_b", "family_001"],
      verifiedLocations: ["Ha Noi"],
      typicalLocations: ["Ha Noi"],
      typicalHours: [8, 9, 10, 12, 19, 20, 21],
      typicalAmounts: { median: 300_000, p75: 1_200_000, p95: 2_000_000 },
      recentTransferCount1h: 4,
    },
    beneficiary: {
      recipientId: "scam_romance_mule",
      isNewRecipient: true,
      hasBeenReported: false,
      isMuleCluster: true,
      isTrusted: false,
    },
  },
];

export function getGuardianScenario(id: GuardianScenarioId) {
  const scenario = guardianScenarios.find((candidate) => candidate.id === id);

  if (!scenario) {
    throw new Error(`Unknown GuardianFlow scenario: ${id}`);
  }

  return scenario;
}
